//! Windows resource embedding: gives zipnest.exe its icon, version metadata,
//! and a real window title. Without this, Explorer/taskbar/shortcuts would
//! fall back to a generic (blank) icon, and the exe would report an empty
//! FileVersion/ProductVersion in its VersionInfo.

use std::env;
use std::fs;
use std::path::Path;

/// Icon (and any other hand-written resources). Contains no VERSIONINFO.
const APP_RC: &str = "src/assets/app.rc";
/// Single source of truth for the shipped version number.
const MAIN_RS: &str = "src/main.rs";

fn main() {
    #[cfg(windows)]
    {
        // Keep the hand-written resources (the icon) working exactly as before.
        embed_resource::compile(APP_RC, embed_resource::NONE);

        // `CURRENT_VERSION` lives in src/main.rs, so the exe has to be rebuilt
        // (and its resource recompiled) whenever that file changes.
        println!("cargo:rerun-if-changed={APP_RC}");
        println!("cargo:rerun-if-changed={MAIN_RS}");

        if let Some(out_dir) = env::var_os("OUT_DIR") {
            let rc = version_rc_path(Path::new(&out_dir));
            if fs::write(&rc, version_rc(&read_current_version())).is_ok() {
                // Compile it as its own .rc: its file stem becomes the output
                // name, so this never overwrites the icon resource.
                embed_resource::compile(&rc, embed_resource::NONE);
            }
        }
    }
}

/// `$OUT_DIR/zipnest_version.rc` — used only as the resource-compiler input, so
/// the stem stays distinct from `app` and the two link args cannot collide.
#[cfg(windows)]
fn version_rc_path(out_dir: &Path) -> std::path::PathBuf {
    out_dir.join("zipnest_version.rc")
}

/// The generated VERSIONINFO resource. `0.3.6` becomes both the numeric
/// `(0,3,6,0)` tuple and the `"0.3.6"` strings.
#[cfg(windows)]
fn version_rc(version: &str) -> String {
    let numbers = version_numbers(version);
    format!(
        r#"// Generated by build.rs from CURRENT_VERSION in src/main.rs -- do not edit.
1 VERSIONINFO
FILEVERSION {a},{b},{c},{d}
PRODUCTVERSION {a},{b},{c},{d}
FILEFLAGSMASK 0x3fL
FILEFLAGS 0x0L
FILEOS 0x40004L
FILETYPE 0x1L
FILESUBTYPE 0x0L
BEGIN
  BLOCK "StringFileInfo"
  BEGIN
    BLOCK "040904b0"
    BEGIN
      VALUE "CompanyName", "ZipNest contributors"
      VALUE "FileDescription", "ZipNest archive manager"
      VALUE "FileVersion", "{v}"
      VALUE "InternalName", "zipnest"
      VALUE "LegalCopyright", "MIT License"
      VALUE "OriginalFilename", "zipnest.exe"
      VALUE "ProductName", "ZipNest"
      VALUE "ProductVersion", "{v}"
    END
  END
  BLOCK "VarFileInfo"
  BEGIN
    VALUE "Translation", 0x0409, 0x04b0
  END
END
"#,
        a = numbers[0],
        b = numbers[1],
        c = numbers[2],
        d = numbers[3],
        v = version,
    )
}

/// `version` split into the four numbers VERSIONINFO wants, zero-filled.
/// Anything unparsable degrades to `0.0.0.0` instead of failing the build.
#[cfg(windows)]
fn version_numbers(version: &str) -> [u32; 4] {
    let mut numbers = [0u32; 4];
    for (slot, part) in numbers.iter_mut().zip(version.split('.')) {
        *slot = part.trim().parse().unwrap_or(0);
    }
    numbers
}

/// Reads `CURRENT_VERSION = "x.y.z"` out of src/main.rs. Never panics: if the
/// file or the constant is missing (or the value is not a version), the build
/// still succeeds and the exe simply reports 0.0.0.
#[cfg(windows)]
fn read_current_version() -> String {
    fs::read_to_string(MAIN_RS)
        .ok()
        .and_then(|source| extract_current_version(&source))
        .unwrap_or_else(|| "0.0.0".to_string())
}

#[cfg(windows)]
fn extract_current_version(source: &str) -> Option<String> {
    let line = source
        .lines()
        .find(|line| line.contains("CURRENT_VERSION") && line.contains('='))?;
    let (_, after_eq) = line.split_once('=')?;
    let (_, after_quote) = after_eq.split_once('"')?;
    let (value, _) = after_quote.split_once('"')?;
    let value = value.trim();
    // Guard against matching some other string on the same line.
    let looks_like_version = !value.is_empty()
        && value.split('.').count() >= 2
        && value.chars().all(|c| c.is_ascii_digit() || c == '.');
    if looks_like_version {
        Some(value.to_string())
    } else {
        None
    }
}

#[cfg(all(test, windows))]
mod tests {
    use super::{extract_current_version, version_numbers, version_rc};

    #[test]
    fn reads_the_declaration_used_by_main_rs() {
        let source = "//! doc\nconst UPDATE_UA: &str = \"ZipNest-Updater/0.3.5\";\nconst CURRENT_VERSION: &str = \"0.3.6\";\n";
        assert_eq!(extract_current_version(source).as_deref(), Some("0.3.6"));
    }

    #[test]
    fn missing_or_malformed_declarations_do_not_parse() {
        assert_eq!(extract_current_version(""), None);
        // Present, but not an assignment: must not be mistaken for the version.
        assert_eq!(extract_current_version("let v = parse_version(CURRENT_VERSION);"), None);
        assert_eq!(extract_current_version("const CURRENT_VERSION: &str = \"abc\";"), None);
    }

    #[test]
    fn numbers_and_strings_agree() {
        assert_eq!(version_numbers("0.3.6"), [0, 3, 6, 0]);
        // Degrades instead of failing the build.
        assert_eq!(version_numbers("0.0.0"), [0, 0, 0, 0]);
        let rc = version_rc("0.3.6");
        assert!(rc.contains("FILEVERSION 0,3,6,0"));
        assert!(rc.contains("PRODUCTVERSION 0,3,6,0"));
        assert!(rc.contains("VALUE \"FileVersion\", \"0.3.6\""));
        assert!(rc.contains("VALUE \"Translation\", 0x0409, 0x04b0"));
    }
}
